/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import java.nio.BufferOverflowException;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {

        System.out.println(new App().getGreeting());
        pickANumberLessThan3(2);
        pickANumberLessThan3(4);
    }

    public static String pickANumberLessThan3 (int someNumber){
        if(someNumber > 7){
            throw new BufferOverflowException();
        }
        if(someNumber > 3){
            throw new IllegalArgumentException("this is too big");
        }

        return "you did good";
    }
}
