/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package internetdemo;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static String goOnInternet() throws IOException {
        URL url = new URL("http://numbersapi.com/11");
        HttpURLConnection numConnection =  (HttpURLConnection) url.openConnection();
        numConnection.setRequestMethod("GET");

        BufferedReader input = new BufferedReader(new InputStreamReader(numConnection.getInputStream()));

        StringBuilder buildy = new StringBuilder();
        String firstLine = input.readLine();
        while(firstLine != null){
            buildy.append(firstLine);
            firstLine = input.readLine();
        }
        return buildy.toString();

    }

    public static String goOnInterNetOrLocal(){
        try {
            System.out.println(goOnInternet());
            return goOnInterNet();
        } catch (IOException e) {
//            e.printStackTrace();
            System.out.println("3 2 1 magic hands! - Professor");
            return goLocal()
        }
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        goOnInterNetOrLocal();


    }
}
